import type { NextPage } from 'next';
import { useState, useEffect } from 'react';
import Head from 'next/head';

async function getDistanceSessions() {
  const res = await fetch('/api/distance-session');
  return await res.json();
}

const Home: NextPage = () => {
  const [distanceSessions, setDistanceSessions] = useState([]);

  const addDistanceSession = async (e: React.SyntheticEvent) => {
    e.preventDefault();

    const target = e.target as typeof e.target & {
      distance: { value: number };
    };

    const distance = Number(target.distance.value);

    const res = await fetch('/api/distance-session', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ distance }),
    });

    if (res.status !== 200) {
      console.error('Something went wrong');
    } else {
      const sessions = await getDistanceSessions();
      setDistanceSessions(sessions);
    }
  };

  useEffect(() => {
    const fetchDistanceSessions = async () => {
      const sessions = await getDistanceSessions();
      setDistanceSessions(sessions);
    };
    fetchDistanceSessions();
  }, []);

  return (
    <div>
      <Head>
        <title>Distance Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-4">
        <form onSubmit={addDistanceSession}>
          <label htmlFor="distance">
            Distance
            <input
              id="distance"
              type="number"
              className="block border-2 border-warm-gray-300 rounded-md"
            />
          </label>
          <button
            type="submit"
            className="px-4 text-white bg-indigo-600 rounded-sm"
          >
            Submit
          </button>
        </form>

        <div>
          <pre className="text-xs">
            {JSON.stringify(distanceSessions, null, 2)}
          </pre>
        </div>
      </main>
    </div>
  );
};

export default Home;
